#!/usr/bin/env python
# expand an IPv6 address
import argparse, socket, binascii, sys, re
parser = argparse.ArgumentParser()
parser.add_argument("ip6addr", help="IPv6 address")
parser.add_argument("left", help="Number of leftmost bytes to output", type=int, nargs="?", default=16)
parser.add_argument("right", help="Number of rightmost bytes to output", type=int, nargs="?", default=16)
args = parser.parse_args()
exp = socket.inet_pton(socket.AF_INET6, args.ip6addr)
hex = binascii.hexlify(exp)
out = hex[:args.left * 2][-args.right * 2:]
if args.right < args.left:
    regex = re.compile(r'(.{1,4})(?=(.{4})+)')
else:
    regex = re.compile(r'(.{4})(?!$)')
sys.stdout.write(regex.sub(r'\1:', out))
