#!/bin/bash
# make solicited-node multicast IPv6 address from IPv6 address
if test $# -ne 1; then
    echo "usage: $0 <ip6addr>" 1>&2
    exit 1
fi
echo -n ff02::1:ff$("$(dirname "$0")/exp6" $1 16 3)
