#!/usr/bin/env python
# convert an IPv4 address into a mulicast MAC address
import argparse, socket, binascii, sys, re

regex = re.compile(r'(.{2})(?!$)')
def fmt(n):
    exp = ''.join([chr(n >> (i * 8) & 255) for i in xrange(5, -1, -1)])
    hex = binascii.hexlify(exp)
    return regex.sub(r'\1:', hex)

parser = argparse.ArgumentParser()
parser.add_argument("ip4addr", help="IPv4 address")
args = parser.parse_args()
ip4addr = args.ip4addr.partition("/")
b = ip4addr[2]
b = int(b) if b else 32
exp = socket.inet_pton(socket.AF_INET, ip4addr[0])
n = long(exp.encode('hex'), 16)
n &= (2 ** 23 - 1)
n |= 0x01005e000000
m = ~(2 ** (23 - max(b - 9, 0)) - 1)
n &= m
sys.stdout.write(fmt(n))
if b < 32:
    sys.stdout.write('/')
    sys.stdout.write(fmt(m))
